version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      - libloader-net

  web:
    build:
      context: .
      dockerfile: libloaderapi/Dockerfile
    container_name: libloader_web
    entrypoint:
      - dotnet
      - libloaderapi.dll
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - JWT_SECRET
    ipc: private
    logging:
      driver: json-file
      options: {}
    ports:
      - 8081:80/tcp
    working_dir: /app
    depends_on:
     - "postgres"
    networks:
      - libloader-net

networks:
    libloader-net:
      driver: bridge