version: '3.4'

services:
  libloaderapi:
    container_name: libloaderapi
    hostname:  libloaderapi
    restart: unless-stopped
    image: ${DOCKER_REGISTRY-}libloaderapi
    build:
      context: .
      dockerfile: libloaderapi/Dockerfile
    ports:
      - 8081:80/tcp
    depends_on:
      - "db"

  db:
    image: postgres
    container_name: db_libloaderapi
    hostname: db
    restart: always
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=boo